#!/usr/bin/env sh

echo
pkill -SIGSTOP studio

printf "============> Suspending Android Studio <============"

gradleCommand="./gradlewSuspend ${@}"
eval ${gradleCommand}
pkill -SIGCONT studio

printf "============> Resume Android Studio <============"
echo